Repository pagopa/pagopa-template-receipt-pdf, pull requests merged in 2023-10, with the labels that each got.

#7 [PRDP-143] feat: Add GHA for automatic pr to notifier
  .github/workflows/update_pdf_engine_template.yml
  .github/workflows/update_receipt_notifier_markdown.yml
  io-message/templates/debtor.json
  io-message/templates/debtor.md
  io-message/templates/helm/values-dev.yaml
  io-message/templates/payer.json
  io-message/templates/payer.md
  receipt/success/pdf/package.json
Labels: enhancement

#10 fix: Update `puppeteer` and `node-version`
  .gitignore
  receipt/success/json/authenticated-pdf.json
  receipt/success/pdf/.node-version
  receipt/success/pdf/package.json
  receipt/success/pdf/yarn.lock
Labels: bug, dependencies

#11 chore: Update template copy, add legal disclaimer
  receipt/plain-text.hbs
  receipt/success/pdf/template.hbs
Labels: enhancement

#12 chore: Add dynamic values for PSP
  receipt/success/json/authenticated-apple-pay-pdf.json
  receipt/success/json/authenticated-extra-fee-pdf.json
  receipt/success/json/authenticated-multiple-cart-items-pdf.json
  receipt/success/json/authenticated-pdf.json
  receipt/success/json/guest-multiple-cart-items-requested-debtor-pdf.json
  receipt/success/json/guest-requested-debtor-pdf.json
  receipt/success/pdf/template.hbs
Labels: enhancement

#13 chore: Add `splitAndSpace` helper for the `Codice avviso` field
  receipt/success/helpers/splitAndSpace.js
  receipt/success/pdf/package.json
  receipt/success/pdf/template.hbs
Labels: enhancement

#14 chore: Make PSP info optional
  receipt/success/pdf/template.hbs
Labels: enhancement

#15 chore: Add `fullName` instead of separated name and surname
  receipt/success/json/authenticated-apple-pay-pdf.json
  receipt/success/json/authenticated-extra-fee-pdf.json
  receipt/success/json/authenticated-multiple-cart-items-pdf.json
  receipt/success/json/authenticated-pdf.json
  receipt/success/pdf/template.hbs
Labels: enhancement

#18 [PRDP-156] fix: Added base64 encoding to subject and markdown
  .github/workflows/update_receipt_notifier_markdown.yml
  io-message/templates/debtor.json
Labels: bug

#20 [PRDP-157] fix: Removed base64 encoding
  .github/workflows/update_receipt_notifier_markdown.yml
Labels: bug

#24 chore: Add local fonts
  receipt/success/pdf/assets/fonts/DM_Mono/DMMono-Medium.ttf
  receipt/success/pdf/assets/fonts/DM_Mono/OFL.txt
  receipt/success/pdf/assets/fonts/Titillium_Web/OFL.txt
  receipt/success/pdf/assets/fonts/Titillium_Web/TitilliumWeb-Bold.ttf
  receipt/success/pdf/assets/fonts/Titillium_Web/TitilliumWeb-Regular.ttf
  receipt/success/pdf/assets/fonts/Titillium_Web/TitilliumWeb-SemiBold.ttf
  receipt/success/pdf/style.css
  receipt/success/pdf/template.hbs
  receipt/success/pdf/yarn.lock
Labels: enhancement

#27 chore: Add dimension limits to the PSP logo
  receipt/success/pdf/style.css
  receipt/success/pdf/template.hbs
Labels: enhancement

#28 chore: Remove useless data from the template
  receipt/success/pdf/template.hbs
Labels: enhancement

#34 chore: Improve the size of the PSP logo
  receipt/success/pdf/style.css
  receipt/success/pdf/template.hbs
Labels: enhancement

#32 [fix-psp-debtor] Extrapolated transaction.psp.name from debtor condition
  receipt/success/pdf/template.hbs
Labels: bug

#35 fix: Fix line-height with long PSP names
  receipt/success/pdf/style.css
  receipt/success/pdf/template.hbs
Labels: bug

#36 chore: Hide PSP logo if payment is not processed by PagoPA main services
  receipt/success/json/authenticated-apple-pay-pdf.json
  receipt/success/json/authenticated-extra-fee-pdf.json
  receipt/success/json/authenticated-multiple-cart-items-pdf.json
  receipt/success/json/authenticated-pdf.json
  receipt/success/json/guest-multiple-cart-items-requested-debtor-pdf.json
  receipt/success/json/guest-requested-debtor-pdf.json
  receipt/success/pdf/template.hbs
Labels: enhancement

#37 Feat add auto push of psp file
  .github/workflows/update_psp_info_file.yml
Labels: enhancement
